export const ERROR_DOMAINS = ['INGRESS', 'QUEUE', 'OUTBOUND', 'ATTACHMENT', 'AI', 'CONFIG', 'ADMIN', 'STORAGE', 'INTERNAL'] as const;
export const ERROR_PROVIDERS = ['NONE', 'CLOUDFLARE_QUEUE', 'D1', 'R2', 'TELEGRAM', 'CHATWOOT', 'AI_PROVIDER'] as const;
export const ERROR_STAGES = [
  'AUTHENTICATE', 'VALIDATE', 'ENQUEUE', 'CLAIM', 'SOURCE_METADATA', 'SOURCE_DOWNLOAD',
  'STORE', 'PREPARE', 'DISPATCH', 'PARSE_RESPONSE', 'PERSIST_RESULT', 'RECONCILE', 'CLEANUP'
] as const;
export const ERROR_CLASSES = [
  'CONFIG', 'AUTH', 'VALIDATION', 'RATE_LIMIT', 'NETWORK', 'TIMEOUT', 'PROVIDER_4XX',
  'PROVIDER_5XX', 'INVALID_PROVIDER_RESPONSE', 'D1', 'QUEUE', 'R2', 'CONCURRENCY',
  'AMBIGUOUS_DELIVERY', 'INTERNAL_INVARIANT'
] as const;
export const RETRYABILITIES = ['AUTOMATIC', 'MANUAL', 'NEVER'] as const;
export const VISIBILITIES = ['NON_VISIBLE', 'VISIBLE'] as const;
export const AMBIGUITIES = ['NONE', 'POSSIBLE', 'CONFIRMED_UNKNOWN'] as const;

export type ErrorDomain = typeof ERROR_DOMAINS[number];
export type ErrorProvider = typeof ERROR_PROVIDERS[number];
export type ErrorStage = typeof ERROR_STAGES[number];
export type ErrorClass = typeof ERROR_CLASSES[number];
export type Retryability = typeof RETRYABILITIES[number];
export type Visibility = typeof VISIBILITIES[number];
export type Ambiguity = typeof AMBIGUITIES[number];

export interface SafeErrorDefinition {
  domain: ErrorDomain;
  provider: ErrorProvider;
  stage: ErrorStage;
  class: ErrorClass;
  retryability: Retryability;
  visibility: Visibility;
  ambiguity: Ambiguity;
}

function definition(
  domain: ErrorDomain,
  provider: ErrorProvider,
  stage: ErrorStage,
  errorClass: ErrorClass,
  retryability: Retryability,
  visibility: Visibility = 'NON_VISIBLE',
  ambiguity: Ambiguity = 'NONE'
): SafeErrorDefinition {
  return { domain, provider, stage, class: errorClass, retryability, visibility, ambiguity };
}

const I = definition;

export const SAFE_ERROR_REGISTRY = {
  INGRESS_AUTH_REJECTED: I('INGRESS', 'NONE', 'AUTHENTICATE', 'AUTH', 'NEVER'),
  INGRESS_PAYLOAD_INVALID: I('INGRESS', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  QUEUE_ENQUEUE_FAILED: I('QUEUE', 'CLOUDFLARE_QUEUE', 'ENQUEUE', 'QUEUE', 'AUTOMATIC'),
  QUEUE_EVENT_VERSION_UNSUPPORTED: I('QUEUE', 'CLOUDFLARE_QUEUE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  QUEUE_EVENT_CLAIM_CONTENDED: I('QUEUE', 'D1', 'CLAIM', 'CONCURRENCY', 'AUTOMATIC'),
  QUEUE_EVENT_PROCESSING_FAILED: I('QUEUE', 'NONE', 'PERSIST_RESULT', 'INTERNAL_INVARIANT', 'MANUAL'),
  QUEUE_RETRY_EXHAUSTED: I('QUEUE', 'CLOUDFLARE_QUEUE', 'PERSIST_RESULT', 'QUEUE', 'MANUAL'),

  D1_READ_FAILED: I('STORAGE', 'D1', 'PREPARE', 'D1', 'AUTOMATIC'),
  D1_WRITE_FAILED: I('STORAGE', 'D1', 'PERSIST_RESULT', 'D1', 'AUTOMATIC'),
  D1_RESULT_PERSIST_FAILED: I('STORAGE', 'D1', 'PERSIST_RESULT', 'D1', 'AUTOMATIC'),
  RUNTIME_CONFIG_READ_FAILED: I('CONFIG', 'D1', 'PREPARE', 'D1', 'AUTOMATIC'),
  RUNTIME_CONFIG_VALUE_INVALID: I('CONFIG', 'D1', 'VALIDATE', 'CONFIG', 'MANUAL'),
  RUNTIME_CONFIG_SECRET_DECRYPT_FAILED: I('CONFIG', 'D1', 'PREPARE', 'CONFIG', 'MANUAL'),
  RUNTIME_CONFIG_VERSION_CONFLICT: I('CONFIG', 'D1', 'CLAIM', 'CONCURRENCY', 'MANUAL'),

  OUTBOUND_PRECONDITION_FAILED: I('OUTBOUND', 'NONE', 'PREPARE', 'CONFIG', 'MANUAL', 'VISIBLE'),
  OUTBOUND_RATE_LIMITED: I('OUTBOUND', 'NONE', 'DISPATCH', 'RATE_LIMIT', 'AUTOMATIC', 'VISIBLE'),
  OUTBOUND_TRANSPORT_AMBIGUOUS: I('OUTBOUND', 'NONE', 'DISPATCH', 'NETWORK', 'MANUAL', 'VISIBLE', 'CONFIRMED_UNKNOWN'),
  OUTBOUND_TIMEOUT_AMBIGUOUS: I('OUTBOUND', 'NONE', 'DISPATCH', 'TIMEOUT', 'MANUAL', 'VISIBLE', 'CONFIRMED_UNKNOWN'),
  OUTBOUND_PROVIDER_4XX_FINAL: I('OUTBOUND', 'NONE', 'DISPATCH', 'PROVIDER_4XX', 'NEVER', 'VISIBLE'),
  OUTBOUND_PROVIDER_5XX_AMBIGUOUS: I('OUTBOUND', 'NONE', 'DISPATCH', 'PROVIDER_5XX', 'MANUAL', 'VISIBLE', 'CONFIRMED_UNKNOWN'),
  OUTBOUND_INVALID_SUCCESS_AMBIGUOUS: I('OUTBOUND', 'NONE', 'PARSE_RESPONSE', 'INVALID_PROVIDER_RESPONSE', 'MANUAL', 'VISIBLE', 'CONFIRMED_UNKNOWN'),
  OUTBOUND_RESULT_PERSIST_AMBIGUOUS: I('OUTBOUND', 'D1', 'PERSIST_RESULT', 'AMBIGUOUS_DELIVERY', 'MANUAL', 'VISIBLE', 'CONFIRMED_UNKNOWN'),
  OUTBOUND_RETRY_EXHAUSTED: I('OUTBOUND', 'NONE', 'DISPATCH', 'RATE_LIMIT', 'MANUAL', 'VISIBLE'),
  OUTBOUND_MANUAL_RECONCILIATION_REQUIRED: I('OUTBOUND', 'NONE', 'RECONCILE', 'AMBIGUOUS_DELIVERY', 'MANUAL', 'VISIBLE', 'CONFIRMED_UNKNOWN'),
  OUTBOUND_RECONCILIATION_NOT_ELIGIBLE: I('OUTBOUND', 'NONE', 'RECONCILE', 'VALIDATION', 'NEVER'),
  CHATWOOT_STATE_READ_FAILED: I('OUTBOUND', 'CHATWOOT', 'SOURCE_METADATA', 'NETWORK', 'AUTOMATIC'),
  CHATWOOT_STATE_INVALID: I('OUTBOUND', 'CHATWOOT', 'PARSE_RESPONSE', 'INVALID_PROVIDER_RESPONSE', 'MANUAL'),
  TOPIC_LIFECYCLE_RECONCILIATION_REQUIRED: I('OUTBOUND', 'TELEGRAM', 'RECONCILE', 'AMBIGUOUS_DELIVERY', 'MANUAL', 'VISIBLE', 'CONFIRMED_UNKNOWN'),
  TOPIC_LIFECYCLE_FINAL_BLOCKED: I('OUTBOUND', 'TELEGRAM', 'RECONCILE', 'VALIDATION', 'MANUAL', 'VISIBLE'),
  TOPIC_LIFECYCLE_SUPERSEDED_BEFORE_SEND: I('OUTBOUND', 'TELEGRAM', 'PREPARE', 'CONCURRENCY', 'NEVER', 'VISIBLE'),
  OUTBOUND_MANUAL_RETRY_NOT_ELIGIBLE: I('OUTBOUND', 'NONE', 'PREPARE', 'VALIDATION', 'NEVER', 'VISIBLE'),
  OUTBOUND_MANUAL_RETRY_TARGET_CHANGED: I('OUTBOUND', 'NONE', 'PREPARE', 'CONFIG', 'MANUAL', 'VISIBLE'),
  OUTBOUND_MANUAL_RETRY_PAYLOAD_UNAVAILABLE: I('OUTBOUND', 'NONE', 'PREPARE', 'VALIDATION', 'NEVER', 'VISIBLE'),
  OUTBOUND_DOMAIN_STATE_CONFLICT: I('OUTBOUND', 'D1', 'PERSIST_RESULT', 'INTERNAL_INVARIANT', 'MANUAL', 'VISIBLE'),
  RECONCILIATION_RATE_LIMITED: I('OUTBOUND', 'CHATWOOT', 'RECONCILE', 'RATE_LIMIT', 'AUTOMATIC'),
  RECONCILIATION_PROVIDER_UNAVAILABLE: I('OUTBOUND', 'CHATWOOT', 'RECONCILE', 'NETWORK', 'AUTOMATIC'),
  RECONCILIATION_PROVIDER_REJECTED: I('OUTBOUND', 'CHATWOOT', 'RECONCILE', 'PROVIDER_4XX', 'MANUAL'),
  RECONCILIATION_INVALID_RESPONSE: I('OUTBOUND', 'CHATWOOT', 'RECONCILE', 'INVALID_PROVIDER_RESPONSE', 'MANUAL'),

  ATTACHMENT_SOURCE_AUTH_FAILED: I('ATTACHMENT', 'NONE', 'SOURCE_DOWNLOAD', 'AUTH', 'NEVER'),
  ATTACHMENT_SOURCE_NOT_FOUND: I('ATTACHMENT', 'NONE', 'SOURCE_DOWNLOAD', 'PROVIDER_4XX', 'NEVER'),
  ATTACHMENT_SOURCE_TOO_LARGE: I('ATTACHMENT', 'NONE', 'SOURCE_METADATA', 'VALIDATION', 'NEVER'),
  ATTACHMENT_SOURCE_RATE_LIMITED: I('ATTACHMENT', 'NONE', 'SOURCE_DOWNLOAD', 'RATE_LIMIT', 'AUTOMATIC'),
  ATTACHMENT_SOURCE_TRANSIENT: I('ATTACHMENT', 'NONE', 'SOURCE_DOWNLOAD', 'NETWORK', 'AUTOMATIC'),
  ATTACHMENT_SOURCE_INVALID: I('ATTACHMENT', 'NONE', 'SOURCE_METADATA', 'VALIDATION', 'NEVER'),
  ATTACHMENT_EXPIRED: I('ATTACHMENT', 'NONE', 'PREPARE', 'VALIDATION', 'NEVER'),
  ATTACHMENT_DELIVERY_AMBIGUOUS: I('ATTACHMENT', 'NONE', 'RECONCILE', 'AMBIGUOUS_DELIVERY', 'MANUAL', 'VISIBLE', 'CONFIRMED_UNKNOWN'),
  ATTACHMENT_DELIVERY_FINAL: I('ATTACHMENT', 'NONE', 'DISPATCH', 'PROVIDER_4XX', 'NEVER', 'VISIBLE'),
  ATTACHMENT_RETRY_EXHAUSTED: I('ATTACHMENT', 'NONE', 'SOURCE_DOWNLOAD', 'NETWORK', 'MANUAL'),
  ATTACHMENT_COUNT_LIMIT: I('ATTACHMENT', 'NONE', 'SOURCE_METADATA', 'VALIDATION', 'NEVER'),

  R2_STORE_TRANSIENT: I('STORAGE', 'R2', 'STORE', 'R2', 'AUTOMATIC'),
  R2_READ_TRANSIENT: I('STORAGE', 'R2', 'PREPARE', 'R2', 'AUTOMATIC'),
  R2_OBJECT_MISSING: I('STORAGE', 'R2', 'PREPARE', 'R2', 'NEVER'),
  R2_OBJECT_TOO_LARGE: I('STORAGE', 'R2', 'PREPARE', 'VALIDATION', 'NEVER'),
  R2_DELETE_TRANSIENT: I('STORAGE', 'R2', 'CLEANUP', 'R2', 'AUTOMATIC'),

  AI_RATE_LIMITED: I('AI', 'AI_PROVIDER', 'DISPATCH', 'RATE_LIMIT', 'AUTOMATIC'),
  AI_TIMEOUT: I('AI', 'AI_PROVIDER', 'DISPATCH', 'TIMEOUT', 'AUTOMATIC'),
  AI_TRANSPORT_ERROR: I('AI', 'AI_PROVIDER', 'DISPATCH', 'NETWORK', 'AUTOMATIC'),
  AI_PROVIDER_4XX: I('AI', 'AI_PROVIDER', 'DISPATCH', 'PROVIDER_4XX', 'NEVER'),
  AI_PROVIDER_5XX: I('AI', 'AI_PROVIDER', 'DISPATCH', 'PROVIDER_5XX', 'AUTOMATIC'),
  AI_INVALID_RESPONSE: I('AI', 'AI_PROVIDER', 'PARSE_RESPONSE', 'INVALID_PROVIDER_RESPONSE', 'AUTOMATIC'),
  AI_CONTEXT_INVALID: I('AI', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  AI_SCOPE_DENIED: I('AI', 'NONE', 'VALIDATE', 'CONFIG', 'NEVER'),
  AI_RETRY_EXHAUSTED: I('AI', 'AI_PROVIDER', 'DISPATCH', 'PROVIDER_5XX', 'MANUAL'),
  AI_LEGACY_FAILURE_UNCLASSIFIED: I('AI', 'NONE', 'PERSIST_RESULT', 'INTERNAL_INVARIANT', 'MANUAL'),

  CONCURRENCY_LEASE_HELD: I('INTERNAL', 'D1', 'CLAIM', 'CONCURRENCY', 'AUTOMATIC'),
  CONCURRENCY_CAS_CONFLICT: I('INTERNAL', 'D1', 'CLAIM', 'CONCURRENCY', 'AUTOMATIC'),
  SUPPORT_PROFILE_STALE: I('CONFIG', 'TELEGRAM', 'VALIDATE', 'CONFIG', 'NEVER'),
  SUPPORT_PROFILE_FUTURE: I('CONFIG', 'TELEGRAM', 'VALIDATE', 'CONFIG', 'AUTOMATIC'),
  TARGET_IDENTITY_CHANGED: I('OUTBOUND', 'NONE', 'PREPARE', 'CONFIG', 'MANUAL', 'VISIBLE'),
  INTERNAL_INVARIANT_VIOLATION: I('INTERNAL', 'NONE', 'PERSIST_RESULT', 'INTERNAL_INVARIANT', 'MANUAL'),

  ADMIN_OPERATION_FAILED: I('ADMIN', 'NONE', 'PERSIST_RESULT', 'INTERNAL_INVARIANT', 'MANUAL'),
  ADMIN_INPUT_INVALID: I('ADMIN', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  ADMIN_SUPPORT_BOT_MUST_DIFFER: I('ADMIN', 'TELEGRAM', 'VALIDATE', 'CONFIG', 'NEVER'),
  ADMIN_PROVIDER_REJECTED: I('ADMIN', 'TELEGRAM', 'DISPATCH', 'PROVIDER_4XX', 'MANUAL'),
  ADMIN_PROVIDER_TRANSIENT: I('ADMIN', 'TELEGRAM', 'DISPATCH', 'PROVIDER_5XX', 'AUTOMATIC'),
  ADMIN_PROVIDER_RATE_LIMITED: I('ADMIN', 'TELEGRAM', 'DISPATCH', 'RATE_LIMIT', 'AUTOMATIC'),
  ADMIN_PROVIDER_TIMEOUT: I('ADMIN', 'TELEGRAM', 'DISPATCH', 'TIMEOUT', 'AUTOMATIC'),
  ADMIN_PROVIDER_TRANSPORT_ERROR: I('ADMIN', 'TELEGRAM', 'DISPATCH', 'NETWORK', 'AUTOMATIC'),
  ADMIN_PROVIDER_INVALID_RESPONSE: I('ADMIN', 'TELEGRAM', 'PARSE_RESPONSE', 'INVALID_PROVIDER_RESPONSE', 'MANUAL'),
  TELEGRAM_TOKEN_INVALID: I('ADMIN', 'TELEGRAM', 'VALIDATE', 'AUTH', 'NEVER'),
  TELEGRAM_GETME_INVALID: I('ADMIN', 'TELEGRAM', 'PARSE_RESPONSE', 'INVALID_PROVIDER_RESPONSE', 'NEVER'),
  TELEGRAM_GROUP_NOT_FORUM: I('ADMIN', 'TELEGRAM', 'VALIDATE', 'VALIDATION', 'NEVER'),
  TELEGRAM_BOT_PERMISSION_MISSING: I('ADMIN', 'TELEGRAM', 'VALIDATE', 'AUTH', 'NEVER'),
  SUPPORT_BOT_UNAVAILABLE: I('ADMIN', 'TELEGRAM', 'PREPARE', 'CONFIG', 'MANUAL'),
  CONFIRMATION_SESSION_MISSING: I('ADMIN', 'D1', 'PREPARE', 'VALIDATION', 'NEVER'),
  CONFIRMATION_INVALID: I('ADMIN', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  CONFIRMATION_REQUIRED: I('ADMIN', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  UNKNOWN_CONFIRMATION: I('ADMIN', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  UNKNOWN_ADMIN_ACTION: I('ADMIN', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_HISTORY_ID: I('ADMIN', 'D1', 'VALIDATE', 'VALIDATION', 'NEVER'),
  HISTORY_NOT_FOUND: I('ADMIN', 'D1', 'PREPARE', 'VALIDATION', 'NEVER'),
  HISTORY_SECRET_INVALID: I('ADMIN', 'D1', 'VALIDATE', 'CONFIG', 'NEVER'),
  DEDICATED_WORKFLOW_REQUIRED: I('ADMIN', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),

  AI_CONFIG_INCOMPLETE: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'CONFIG', 'MANUAL'),
  AI_CANDIDATE_FAILED: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'CONFIG', 'MANUAL'),
  CHATWOOT_CONFIG_INCOMPLETE: I('CONFIG', 'CHATWOOT', 'VALIDATE', 'CONFIG', 'MANUAL'),
  CHATWOOT_PROFILE_REJECTED: I('CONFIG', 'CHATWOOT', 'VALIDATE', 'PROVIDER_4XX', 'MANUAL'),
  CHATWOOT_PROFILE_TIMEOUT: I('CONFIG', 'CHATWOOT', 'VALIDATE', 'TIMEOUT', 'AUTOMATIC'),
  CHATWOOT_PROFILE_TRANSPORT_ERROR: I('CONFIG', 'CHATWOOT', 'VALIDATE', 'NETWORK', 'AUTOMATIC'),

  RUNTIME_CONFIG_INVALID_ENCODING: I('CONFIG', 'D1', 'VALIDATE', 'CONFIG', 'NEVER'),
  RUNTIME_CONFIG_MASTER_KEY_INVALID: I('CONFIG', 'NONE', 'VALIDATE', 'CONFIG', 'NEVER'),
  RUNTIME_CONFIG_MALFORMED_ROW: I('CONFIG', 'D1', 'VALIDATE', 'CONFIG', 'MANUAL'),
  CONFIG_KIND_MISMATCH: I('CONFIG', 'D1', 'VALIDATE', 'CONFIG', 'NEVER'),
  AI_LEASE_TOO_SHORT: I('CONFIG', 'NONE', 'VALIDATE', 'CONFIG', 'NEVER'),
  INVALID_PROVIDER_URL: I('CONFIG', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_ALLOWED_HOSTS: I('CONFIG', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_TELEGRAM_PROFILE: I('CONFIG', 'TELEGRAM', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_TELEGRAM_GROUP: I('CONFIG', 'TELEGRAM', 'VALIDATE', 'VALIDATION', 'NEVER'),
  UNKNOWN_CONFIG_KEY: I('CONFIG', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_AI_MODEL: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_SECRET: I('CONFIG', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_SYSTEM_PROMPT: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_AI_TIMEOUT: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_AI_CONTEXT_MESSAGES: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_AI_CONTEXT_CHARS: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_AI_LEASE: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_AI_PAUSE_TIMEOUT: I('CONFIG', 'AI_PROVIDER', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_ATTACHMENT_SIZE: I('CONFIG', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_ATTACHMENT_COUNT: I('CONFIG', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_ATTACHMENT_TTL: I('CONFIG', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  INVALID_ATTACHMENT_TIMEOUT: I('CONFIG', 'NONE', 'VALIDATE', 'VALIDATION', 'NEVER'),
  STALE_AI_COMMAND: I('OUTBOUND', 'TELEGRAM', 'PREPARE', 'CONCURRENCY', 'NEVER', 'VISIBLE'),
  CANCELLED_BY_HANDOFF: I('AI', 'NONE', 'PREPARE', 'CONCURRENCY', 'NEVER'),
  DISCARDED_STALE: I('AI', 'NONE', 'PREPARE', 'CONCURRENCY', 'NEVER')
} as const satisfies Record<string, SafeErrorDefinition>;

export type SafeErrorCode = keyof typeof SAFE_ERROR_REGISTRY;

export function isSafeErrorCode(value: unknown): value is SafeErrorCode {
  return typeof value === 'string' && Object.prototype.hasOwnProperty.call(SAFE_ERROR_REGISTRY, value);
}

export function getSafeErrorDefinition(code: SafeErrorCode): SafeErrorDefinition {
  return SAFE_ERROR_REGISTRY[code];
}
